version: 3

includes:
    proto:
        taskfile: ./proto/taskfile.yml
        dir: ./proto
    sdk:
        taskfile: ./sdk/taskfile.yml
        dir: ./sdk
    spec:
        taskfile: ./spec/taskfile.yml
        dir: ./spec

tasks:
    default:
        desc: Show all available tasks
        silent: true
        cmds:
            - task --list-all
