/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_DIRECTMQ_V1_DIRECTMQ_V1_PUBLISH_PB_H_INCLUDED
#define PB_DIRECTMQ_V1_DIRECTMQ_V1_PUBLISH_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _directmq_v1_DeliveryStrategy {
    directmq_v1_DeliveryStrategy_DELIVERY_STRATEGY_AT_LEAST_ONCE_UNSPECIFIED = 0,
    directmq_v1_DeliveryStrategy_DELIVERY_STRATEGY_AT_MOST_ONCE = 1
} directmq_v1_DeliveryStrategy;

/* Struct definitions */
typedef struct _directmq_v1_Publish {
    char *topic;
    directmq_v1_DeliveryStrategy *delivery_strategy;
    uint64_t *size;
    pb_bytes_array_t *payload;
} directmq_v1_Publish;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _directmq_v1_DeliveryStrategy_MIN directmq_v1_DeliveryStrategy_DELIVERY_STRATEGY_AT_LEAST_ONCE_UNSPECIFIED
#define _directmq_v1_DeliveryStrategy_MAX directmq_v1_DeliveryStrategy_DELIVERY_STRATEGY_AT_MOST_ONCE
#define _directmq_v1_DeliveryStrategy_ARRAYSIZE ((directmq_v1_DeliveryStrategy)(directmq_v1_DeliveryStrategy_DELIVERY_STRATEGY_AT_MOST_ONCE+1))

#define directmq_v1_Publish_delivery_strategy_ENUMTYPE directmq_v1_DeliveryStrategy


/* Initializer values for message structs */
#define directmq_v1_Publish_init_default         {NULL, NULL, NULL, NULL}
#define directmq_v1_Publish_init_zero            {NULL, NULL, NULL, NULL}

/* Field tags (for use in manual encoding/decoding) */
#define directmq_v1_Publish_topic_tag            1
#define directmq_v1_Publish_delivery_strategy_tag 2
#define directmq_v1_Publish_size_tag             3
#define directmq_v1_Publish_payload_tag          4

/* Struct field encoding specification for nanopb */
#define directmq_v1_Publish_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   topic,             1) \
X(a, POINTER,  SINGULAR, UENUM,    delivery_strategy,   2) \
X(a, POINTER,  SINGULAR, UINT64,   size,              3) \
X(a, POINTER,  SINGULAR, BYTES,    payload,           4)
#define directmq_v1_Publish_CALLBACK NULL
#define directmq_v1_Publish_DEFAULT NULL

extern const pb_msgdesc_t directmq_v1_Publish_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define directmq_v1_Publish_fields &directmq_v1_Publish_msg

/* Maximum encoded size of messages (where known) */
/* directmq_v1_Publish_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
