/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_DIRECTMQ_V1_DIRECTMQ_V1_SUBSCRIBE_PB_H_INCLUDED
#define PB_DIRECTMQ_V1_DIRECTMQ_V1_SUBSCRIBE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _directmq_v1_Subscribe {
    char *topic;
} directmq_v1_Subscribe;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define directmq_v1_Subscribe_init_default       {NULL}
#define directmq_v1_Subscribe_init_zero          {NULL}

/* Field tags (for use in manual encoding/decoding) */
#define directmq_v1_Subscribe_topic_tag          1

/* Struct field encoding specification for nanopb */
#define directmq_v1_Subscribe_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   topic,             1)
#define directmq_v1_Subscribe_CALLBACK NULL
#define directmq_v1_Subscribe_DEFAULT NULL

extern const pb_msgdesc_t directmq_v1_Subscribe_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define directmq_v1_Subscribe_fields &directmq_v1_Subscribe_msg

/* Maximum encoded size of messages (where known) */
/* directmq_v1_Subscribe_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
