version: 3

tasks:
    default:
        desc: Show all available tasks
        silent: true
        cmds:
            - task --list-all

    clean:
        desc: Clean the DirectMQ C++ SDK test agent build directory
        silent: true
        cmds:
            - echo "Cleaning build directory"
            - rm -rf build

    build:
        desc: Build the DirectMQ C++ SDK test agent
        silent: true
        cmds:
            - echo "Building DirectMQ C++ SDK"
            - cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug
            - cmake --build build

    format:
        desc: Format the DirectMQ C++ SDK test agent source code
        silent: true
        cmds:
            - echo "Formatting source code"
            - find . -path ./build -prune -o \( -name '*.h' -o -name '*.hpp' -o -name '*.cpp' \) -print | xargs clang-format -i -style=file

    analyze:
        desc: Run static analysis on the DirectMQ C++ SDK test agent source code
        silent: true
        cmds:
            - echo "Analyzing source code"
            - cmake -B build -S . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            - find . -path ./build -prune -o \( -name '*.h' -o -name '*.hpp' -o -name '*.cpp' \) -print | xargs clang-tidy -p build

    run:
        desc: Run the DirectMQ C++ SDK test agent
        silent: false
        cmds:
            - echo "Running DirectMQ C++ SDK"
            - ./build/directmq-sdk-agent
