version: 3

tasks:
    default:
        desc: Show all available tasks
        silent: true
        cmds:
            - task --list-all

    clean:
        desc: Clean the DirectMQ C++ SDK test agent build directory
        silent: true
        cmds:
            - echo "Cleaning DirectMQ C++ SDK test agent build directory"
            - rm -rf build

    install:
        desc: Install the DirectMQ C++ SDK test agent dependencies
        silent: true
        cmds:
            - echo "Installing DirectMQ C++ SDK test agent dependencies"
            - conan install . -sbuild_type=Debug --build=missing --deployer=direct_deploy --deployer-folder=build/_deps
            - cmake --preset conan-debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DFETCHCONTENT_BASE_DIR=./build/_deps -B build/Debug -S .

    build:
        desc: Build the DirectMQ C++ SDK test agent
        silent: true
        cmds:
            - echo "Building DirectMQ C++ SDK test agent"
            - cmake --build --preset conan-debug

    format:
        desc: Format the DirectMQ C++ SDK test agent source code
        silent: true
        cmds:
            - echo "Formatting source code"
            - find . -path ./build -prune -o \( -name '*.h' -o -name '*.hpp' -o -name '*.cpp' \) -print | xargs clang-format -i -style=file

    analyze:
        desc: Run static analysis on the DirectMQ C++ SDK test agent source code
        silent: true
        cmds:
            - echo "Analyzing source code"
            - find . -path ./build -prune -o \( -name '*.h' -o -name '*.hpp' -o -name '*.cpp' \) -print | xargs clang-tidy -p build/Debug
