/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "directmq/v1/connection.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(directmq_v1_SupportedProtocolVersions, directmq_v1_SupportedProtocolVersions, AUTO)


PB_BIND(directmq_v1_InitConnection, directmq_v1_InitConnection, AUTO)


PB_BIND(directmq_v1_ConnectionAccepted, directmq_v1_ConnectionAccepted, AUTO)


PB_BIND(directmq_v1_GracefullyClose, directmq_v1_GracefullyClose, AUTO)


PB_BIND(directmq_v1_TerminateNetwork, directmq_v1_TerminateNetwork, AUTO)



