version: 3

tasks:
    default:
        desc: Show all available tasks
        silent: true
        cmds:
            - task --list-all

    clean:
        desc: Clean the DirectMQ Go SDK testing agent build directory
        silent: true
        cmds:
            - echo "Cleaning build directory"
            - rm -rf bin

    build:
        desc: Build the DirectMQ Go SDK testing agent
        silent: true
        cmds:
            - echo "Building DirectMQ Go SDK testing agent"
            - go build -buildvcs=false -gcflags="all=-N -l" -o bin/go-agent
