/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "directmq/v1/publish.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(directmq_v1_Publish, directmq_v1_Publish, AUTO)




