/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_DIRECTMQ_V1_DIRECTMQ_V1_UNSUBSCRIBE_PB_H_INCLUDED
#define PB_DIRECTMQ_V1_DIRECTMQ_V1_UNSUBSCRIBE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _directmq_v1_Unsubscribe {
    pb_callback_t topic;
} directmq_v1_Unsubscribe;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define directmq_v1_Unsubscribe_init_default     {{{NULL}, NULL}}
#define directmq_v1_Unsubscribe_init_zero        {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define directmq_v1_Unsubscribe_topic_tag        1

/* Struct field encoding specification for nanopb */
#define directmq_v1_Unsubscribe_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   topic,             1)
#define directmq_v1_Unsubscribe_CALLBACK pb_default_field_callback
#define directmq_v1_Unsubscribe_DEFAULT NULL

extern const pb_msgdesc_t directmq_v1_Unsubscribe_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define directmq_v1_Unsubscribe_fields &directmq_v1_Unsubscribe_msg

/* Maximum encoded size of messages (where known) */
/* directmq_v1_Unsubscribe_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
