// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: directmq/v1/connection.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SupportedProtocolVersions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupportedProtocolVersions []uint32 `protobuf:"varint,1,rep,packed,name=supported_protocol_versions,json=supportedProtocolVersions,proto3" json:"supported_protocol_versions,omitempty"`
}

func (x *SupportedProtocolVersions) Reset() {
	*x = SupportedProtocolVersions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_directmq_v1_connection_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupportedProtocolVersions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedProtocolVersions) ProtoMessage() {}

func (x *SupportedProtocolVersions) ProtoReflect() protoreflect.Message {
	mi := &file_directmq_v1_connection_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedProtocolVersions.ProtoReflect.Descriptor instead.
func (*SupportedProtocolVersions) Descriptor() ([]byte, []int) {
	return file_directmq_v1_connection_proto_rawDescGZIP(), []int{0}
}

func (x *SupportedProtocolVersions) GetSupportedProtocolVersions() []uint32 {
	if x != nil {
		return x.SupportedProtocolVersions
	}
	return nil
}

type InitConnection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxMessageSize uint64 `protobuf:"varint,1,opt,name=max_message_size,json=maxMessageSize,proto3" json:"max_message_size,omitempty"`
}

func (x *InitConnection) Reset() {
	*x = InitConnection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_directmq_v1_connection_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitConnection) ProtoMessage() {}

func (x *InitConnection) ProtoReflect() protoreflect.Message {
	mi := &file_directmq_v1_connection_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitConnection.ProtoReflect.Descriptor instead.
func (*InitConnection) Descriptor() ([]byte, []int) {
	return file_directmq_v1_connection_proto_rawDescGZIP(), []int{1}
}

func (x *InitConnection) GetMaxMessageSize() uint64 {
	if x != nil {
		return x.MaxMessageSize
	}
	return 0
}

type ConnectionAccepted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxMessageSize uint64 `protobuf:"varint,1,opt,name=max_message_size,json=maxMessageSize,proto3" json:"max_message_size,omitempty"`
}

func (x *ConnectionAccepted) Reset() {
	*x = ConnectionAccepted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_directmq_v1_connection_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionAccepted) ProtoMessage() {}

func (x *ConnectionAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_directmq_v1_connection_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionAccepted.ProtoReflect.Descriptor instead.
func (*ConnectionAccepted) Descriptor() ([]byte, []int) {
	return file_directmq_v1_connection_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectionAccepted) GetMaxMessageSize() uint64 {
	if x != nil {
		return x.MaxMessageSize
	}
	return 0
}

type GracefullyClose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *GracefullyClose) Reset() {
	*x = GracefullyClose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_directmq_v1_connection_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GracefullyClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GracefullyClose) ProtoMessage() {}

func (x *GracefullyClose) ProtoReflect() protoreflect.Message {
	mi := &file_directmq_v1_connection_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GracefullyClose.ProtoReflect.Descriptor instead.
func (*GracefullyClose) Descriptor() ([]byte, []int) {
	return file_directmq_v1_connection_proto_rawDescGZIP(), []int{3}
}

func (x *GracefullyClose) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TerminateNetwork struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *TerminateNetwork) Reset() {
	*x = TerminateNetwork{}
	if protoimpl.UnsafeEnabled {
		mi := &file_directmq_v1_connection_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TerminateNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateNetwork) ProtoMessage() {}

func (x *TerminateNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_directmq_v1_connection_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateNetwork.ProtoReflect.Descriptor instead.
func (*TerminateNetwork) Descriptor() ([]byte, []int) {
	return file_directmq_v1_connection_proto_rawDescGZIP(), []int{4}
}

func (x *TerminateNetwork) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_directmq_v1_connection_proto protoreflect.FileDescriptor

var file_directmq_v1_connection_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6d, 0x71, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6d, 0x71, 0x2e, 0x76, 0x31, 0x22, 0x5b, 0x0a, 0x19, 0x53,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3e, 0x0a, 0x1b, 0x73, 0x75, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x19, 0x73,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x3a, 0x0a, 0x0e, 0x49, 0x6e, 0x69, 0x74,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x10, 0x6d, 0x61,
	0x78, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x6d, 0x61, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x22, 0x3e, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x6d, 0x61,
	0x78, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x6d, 0x61, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x22, 0x29, 0x0a, 0x0f, 0x47, 0x72, 0x61, 0x63, 0x65, 0x66, 0x75, 0x6c,
	0x6c, 0x79, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22,
	0x2a, 0x0a, 0x10, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x42, 0x0c, 0x5a, 0x0a, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_directmq_v1_connection_proto_rawDescOnce sync.Once
	file_directmq_v1_connection_proto_rawDescData = file_directmq_v1_connection_proto_rawDesc
)

func file_directmq_v1_connection_proto_rawDescGZIP() []byte {
	file_directmq_v1_connection_proto_rawDescOnce.Do(func() {
		file_directmq_v1_connection_proto_rawDescData = protoimpl.X.CompressGZIP(file_directmq_v1_connection_proto_rawDescData)
	})
	return file_directmq_v1_connection_proto_rawDescData
}

var file_directmq_v1_connection_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_directmq_v1_connection_proto_goTypes = []interface{}{
	(*SupportedProtocolVersions)(nil), // 0: directmq.v1.SupportedProtocolVersions
	(*InitConnection)(nil),            // 1: directmq.v1.InitConnection
	(*ConnectionAccepted)(nil),        // 2: directmq.v1.ConnectionAccepted
	(*GracefullyClose)(nil),           // 3: directmq.v1.GracefullyClose
	(*TerminateNetwork)(nil),          // 4: directmq.v1.TerminateNetwork
}
var file_directmq_v1_connection_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_directmq_v1_connection_proto_init() }
func file_directmq_v1_connection_proto_init() {
	if File_directmq_v1_connection_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_directmq_v1_connection_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupportedProtocolVersions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_directmq_v1_connection_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitConnection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_directmq_v1_connection_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionAccepted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_directmq_v1_connection_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GracefullyClose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_directmq_v1_connection_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TerminateNetwork); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_directmq_v1_connection_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_directmq_v1_connection_proto_goTypes,
		DependencyIndexes: file_directmq_v1_connection_proto_depIdxs,
		MessageInfos:      file_directmq_v1_connection_proto_msgTypes,
	}.Build()
	File_directmq_v1_connection_proto = out.File
	file_directmq_v1_connection_proto_rawDesc = nil
	file_directmq_v1_connection_proto_goTypes = nil
	file_directmq_v1_connection_proto_depIdxs = nil
}
