version: 3

tasks:
    default:
        desc: Show all available tasks
        silent: true
        cmds:
            - task --list-all

    clean:
        desc: Clean the DirectMQ C++ SDK build directory
        silent: true
        cmds:
            - rm -rf build

    build:
        desc: Build the DirectMQ C++ SDK
        silent: true
        cmds:
            - cmake -B build -S .
            - cmake --build build

    test:
        desc: Run the DirectMQ C++ SDK tests
        silent: true
        cmds:
            - cmake -B build -S .
            - cmake --build build --target test
            - ctest --test-dir build

    run:
        desc: Run the DirectMQ C++ SDK example
        silent: true
        cmds:
            - cmake -B build -S .
            - cmake --build build
            - ./build/directmq-sdk

    dev:
        desc: Compile and run the DirectMQ C++ SDK tests
        silent: true
        watch: true
        interval: 500ms
        sources:
            - src/**/*.cpp
            - test/**/*.cpp
        cmds:
            - task: build
            - task: test
