version: 3

tasks:
    default:
        desc: Show all available tasks
        silent: true
        cmds:
            - task --list-all

    install:
        desc: Initialize the DirectMQ C++ SDK dependencies
        silent: true
        cmds:
            - echo Installing dependencies

            - echo Installing nanopb
            - rm -rf lib/nanopb
            - git clone https://github.com/nanopb/nanopb.git lib/nanopb

            - echo installing catch2
            - rm -rf lib/catch2
            - git clone --branch v2.x https://github.com/catchorg/Catch2.git lib/catch2
            - cd lib/catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF
            - cd lib/catch2 && cmake --build build/ --target install

    clean:
        desc: Clean the DirectMQ C++ SDK build directory
        silent: true
        cmds:
            - echo "Cleaning build directory"
            - rm -rf build

    build:
        desc: Build the DirectMQ C++ SDK
        silent: true
        cmds:
            - echo "Building DirectMQ C++ SDK"
            - cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug
            - cmake --build build

    format:
        desc: Format the DirectMQ C++ SDK source code
        silent: true
        cmds:
            - echo "Formatting source code"
            - find include src test -name '*.h' -o -name '*.hpp' -o -name '*.cpp' | xargs clang-format -i -style=file

    analyze:
        desc: Run static analysis on the DirectMQ C++ SDK source code
        silent: true
        cmds:
            - echo "Analyzing source code"
            - cmake -B build -S . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            - find include src test -name '*.h' -o -name '*.hpp' -o -name '*.cpp' | xargs clang-tidy -p build

    test:
        desc: Run the DirectMQ C++ SDK tests
        silent: true
        cmds:
            - echo "Running C++ SDK tests"
            - cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug
            - ctest --test-dir build --output-on-failure

    run:
        desc: Run the DirectMQ C++ SDK example
        silent: true
        cmds:
            - cmake -B build -S .
            - cmake --build build
            - ./build/directmq-sdk

    dev:
        desc: Compile and run the DirectMQ C++ SDK tests
        silent: true
        watch: true
        interval: 500ms
        sources:
            - lib/**/*.*
            - include/**/*.*
            - src/**/*.*
            - test/**/*.*
        cmds:
            - clear
            - task: format
            # - task: analyze - TODO: Fix the clang-tidy warnings
            - task: clean
            - task: build
            - task: test
