version: 3

tasks:
    default:
        desc: Show all available tasks
        silent: true
        cmds:
            - task --list-all

    clean:
        desc: Clean the DirectMQ C++ SDK build directory
        silent: true
        cmds:
            - rm -rf build

    build:
        desc: Build the DirectMQ C++ SDK
        silent: true
        cmds:
            - cmake -B build -S .
            - cmake --build build

    lint:
        desc: Lint the DirectMQ C++ SDK source code
        silent: true
        cmds:
            - find include src test -name '*.h' -o -name '*.hpp' -o -name '*.cpp' | xargs clang-format -i -style=file

    test:
        desc: Run the DirectMQ C++ SDK tests
        silent: true
        cmds:
            - cmake -B build -S .
            - ctest --test-dir build --output-on-failure

    run:
        desc: Run the DirectMQ C++ SDK example
        silent: true
        cmds:
            - cmake -B build -S .
            - cmake --build build
            - ./build/directmq-sdk

    dev:
        desc: Compile and run the DirectMQ C++ SDK tests
        silent: true
        watch: true
        interval: 500ms
        sources:
            - lib/**/*.*
            - include/**/*.*
            - src/**/*.*
            - test/**/*.*
        cmds:
            - clear
            - echo "Linting source code"
            - task: lint
            - echo "Cleaning build directory"
            - task: clean
            - echo "Building DirectMQ C++ SDK"
            - task: build
            - echo "Running tests"
            - task: test
