version: 3

tasks:
    default:
        desc: Show all available tasks
        silent: true
        cmds:
            - task --list-all

    clean:build:
        desc: Clean the DirectMQ C++ SDK build directory
        silent: true
        aliases:
            - clean
        cmds:
            - echo "Cleaning C++ SDK build directory"
            - rm -rf rm -rf build/Debug build/Release

    clean:deps:
        desc: Clean the DirectMQ C++ SDK dependencies
        silent: true
        cmds:
            - echo "Cleaning C++ SDK dependencies"
            - rm -rf build/_deps

    conan:install:
        desc: Install the DirectMQ C++ SDK dependencies
        silent: true
        requires:
            vars: [BUILD_TYPE]
        cmds:
            - echo "Installing C++ SDK {{.BUILD_TYPE}} dependencies"
            - conan install . -sbuild_type={{.BUILD_TYPE}} --build=missing

    conan:deploy:
        desc: Deploy the DirectMQ C++ SDK dependencies
        silent: true
        internal: true
        cmds:
            - echo "Deploying C++ SDK dependencies"
            - conan install . -sbuild_type=Debug --deployer=direct_deploy --deployer-folder=build/_deps

    cmake:generate:
        desc: Generate cmake build configuration
        internal: true
        silent: true
        requires:
            vars: [BUILD_TYPE, DMQ_BUILD_TESTS]
        cmds:
            - echo "Generating cmake configuration for {{.BUILD_TYPE | lower}} build"
            - cmake --preset conan-{{.BUILD_TYPE | lower}} -B build/{{.BUILD_TYPE}} -S . -DDMQ_BUILD_TESTS={{.DMQ_BUILD_TESTS}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DFETCHCONTENT_BASE_DIR=./build/_deps

    install:
        desc: Install the DirectMQ C++ SDK dependencies
        silent: true
        cmds:
            - task: conan:install
              vars:
                BUILD_TYPE: Debug

            - task: cmake:generate
              vars:
                  BUILD_TYPE: Debug
                  DMQ_BUILD_TESTS: ON

            - task: conan:install
              vars:
                BUILD_TYPE: Release

            - task: cmake:generate
              vars:
                  BUILD_TYPE: Release
                  DMQ_BUILD_TESTS: OFF

            - task: conan:deploy

    build:debug:
        desc: Build the DirectMQ C++ SDK in debug mode
        silent: true
        aliases:
            - build
        cmds:
            - echo "Building DirectMQ C++ SDK in debug mode"
            - cmake --build --preset conan-debug

    build:release:
        desc: Build the DirectMQ C++ SDK in release mode
        silent: true
        cmds:
            - echo "Building DirectMQ C++ SDK in release mode"
            - cmake --build --preset conan-release

    format:
        desc: Format the DirectMQ C++ SDK source code
        silent: true
        cmds:
            - echo "Formatting source code"
            - find include src test -name '*.h' -o -name '*.hpp' -o -name '*.cpp' | xargs clang-format -i -style=file

    analyze:
        desc: Run static analysis on the DirectMQ C++ SDK source code
        silent: true
        cmds:
            - echo "Analyzing C++ SDK source code"
            - find include src test -name '*.h' -o -name '*.hpp' -o -name '*.cpp' | xargs clang-tidy -p build/Debug

    test:
        desc: Run the DirectMQ C++ SDK tests
        silent: true
        cmds:
            - echo "Running C++ SDK tests"
            - ctest --test-dir build/Debug --output-on-failure

    dev:
        desc: Compile and run the DirectMQ C++ SDK tests
        silent: true
        watch: true
        interval: 500ms
        sources:
            - lib/**/*.*
            - include/**/*.*
            - src/**/*.*
            - test/**/*.*
        cmds:
            - clear
            - task: format
            - task: build
            - task: test
