version: 3

tasks:
    default:
        desc: Show all available tasks
        silent: true
        cmds:
            - task --list-all

    clean:
        desc: Clean the DirectMQ C++ SDK build directory
        silent: true
        cmds:
            - echo "Cleaning C++ SDK build directory"
            - rm -rf build/debug build/release

    clean:all:
        desc: Clean the DirectMQ C++ SDK build and dependencies directories
        silent: true
        cmds:
            - echo "Cleaning build and dependencies directories"
            - rm -rf build

    install:
        desc: Install the DirectMQ C++ SDK dependencies
        silent: true
        cmds:
            - echo "Installing C++ SDK dependencies"
            - conan install . -sbuild_type=Debug -of=conan/debug --build=missing

    generate:
        desc: Generate cmake build configuration
        internal: true
        silent: true
        cmds:
            - echo "Generating cmake configuration for {{.BUILD_DIRECTORY}}"
            - cmake -B {{.BUILD_DIRECTORY}} -S . -DCMAKE_BUILD_TYPE={{.CMAKE_BUILD_TYPE}} -DDMQ_BUILD_TESTS={{.DMQ_BUILD_TESTS}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DFETCHCONTENT_BASE_DIR=./build/_deps

    build:
        desc: Build the DirectMQ C++ SDK in debug mode
        silent: true
        cmds:
            - echo "Building DirectMQ C++ SDK in debug mode"

            - task: generate
              vars:
                  BUILD_DIRECTORY: build/debug
                  CMAKE_BUILD_TYPE: Debug
                  DMQ_BUILD_TESTS: ON

            - echo "Building sdk"
            - cmake --build build/debug

    release:
        desc: Build the DirectMQ C++ SDK in release mode
        silent: true
        cmds:
            - echo "Building DirectMQ C++ SDK in release mode"

            - task: generate
              vars:
                  BUILD_DIRECTORY: build/release
                  CMAKE_BUILD_TYPE: Release
                  DMQ_BUILD_TESTS: OFF

            - echo "Building sdk"
            - cmake --build build/release

    format:
        desc: Format the DirectMQ C++ SDK source code
        silent: true
        cmds:
            - echo "Formatting source code"
            - find include src test -name '*.h' -o -name '*.hpp' -o -name '*.cpp' | xargs clang-format -i -style=file

    analyze:
        desc: Run static analysis on the DirectMQ C++ SDK source code
        silent: true
        cmds:
            - echo "Analyzing C++ SDK source code"

            - task: generate
              vars:
                  BUILD_DIRECTORY: build/debug
                  CMAKE_BUILD_TYPE: Debug
                  DMQ_BUILD_TESTS: OFF

            - find include src test -name '*.h' -o -name '*.hpp' -o -name '*.cpp' | xargs clang-tidy -p build/debug

    test:
        desc: Run the DirectMQ C++ SDK tests
        silent: true
        cmds:
            - echo "Running C++ SDK tests"
            - ctest --test-dir build/debug --output-on-failure

    dev:
        desc: Compile and run the DirectMQ C++ SDK tests
        silent: true
        watch: true
        interval: 500ms
        sources:
            - lib/**/*.*
            - include/**/*.*
            - src/**/*.*
            - test/**/*.*
        cmds:
            - clear
            - task: format
            # - task: analyze - TODO: Fix the clang-tidy warnings
            - task: clean
            - task: build
            - task: test
